apiVersion: v1
kind: Service
metadata:
  name: simpleapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: simpleapp
    type: frontend
