apiVersion: v1
kind: Service
metadata:
  name: simpleapp-backend
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: simpleapp
    type: backend
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-redis
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    app: simpleapp
    type: redis
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-frontend
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080
  selector:
    app: simpleapp
    type: frontend